# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/beevik/etree"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/dchest/uniuri"
  revision = "8902c56451e9b58ff940bbe5fec35d5f9c04584a"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "v3.0.0"

[[override]]
  name = "github.com/jonboulle/clockwork"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/kr/pretty"
  revision = "cfb55aafdaf3ec08f0db22699ab822c50091b1c4"

[[override]]
  name = "github.com/kr/text"
  revision = "7cafcd837844e784b526369c9bce262804aebc60"

[[constraint]]
  name = "github.com/russellhaering/goxmldsig"
  revision = "b7efc6231e45b10bfd779852831c8bb59b350ec5"

[[constraint]]
  name = "github.com/zenazn/goji"
  version = "v1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/check.v1"
  revision = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
